<#
.SYNOPSIS
    Remediation script for Intune - Generates orphaned profile reports (Intune Logs Only)
.DESCRIPTION
    - This is a NO-ACTION remediation script (reporting only)
    - Collects the JSON report generated by detection script
    - Converts to CSV format for easy analysis
    - Saves reports locally for reference
    - Reports visible directly in Intune logs/troubleshooting
    - Does NOT delete or modify any profiles
.NOTES
    Run as: SYSTEM account (Intune manages this)
    Execution Policy: Bypass required
    Reports accessed via: Intune Admin Center > Device > Troubleshoot + Support > Recent Runs
#>

param(
    [string]$ReportPath = "C:\Windows\Temp\OrphanedProfiles.json",
    [string]$LocalArchivePath = "C:\Windows\Temp\IntuneReports"
)

$ErrorActionPreference = "Continue"
$VerbosePreference = "Continue"

Write-Verbose "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] Starting remediation (reporting) script..."
Write-Verbose "Report Path: $ReportPath"

# Create local archive directory
if (-not (Test-Path $LocalArchivePath)) {
    try {
        New-Item -ItemType Directory -Path $LocalArchivePath -Force -ErrorAction Stop | Out-Null
        Write-Verbose "Created directory: $LocalArchivePath"
    }
    catch {
        Write-Verbose "Warning: Could not create directory $LocalArchivePath : $_"
    }
}

# Check if detection report exists
if (-not (Test-Path $ReportPath)) {
    Write-Verbose "No detection report found at $ReportPath - no orphaned profiles detected."
    Write-Output "Status: No orphaned profiles detected on this device."
    exit 0
}

# Read the JSON report
try {
    $Report = Get-Content -Path $ReportPath -Raw | ConvertFrom-Json
    Write-Verbose "Report loaded successfully: $($Report.OrphanedCount) orphaned profiles found"
}
catch {
    Write-Verbose "Failed to parse report: $_"
    Write-Output "Error: Could not read report file."
    exit 1
}

# Generate timestamped filename
$Timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$ComputerName = $env:COMPUTERNAME
$ReportFileName = "${ComputerName}_OrphanedProfiles_${Timestamp}"

# Save JSON report locally
try {
    $LocalJsonPath = Join-Path $LocalArchivePath "${ReportFileName}.json"
    Copy-Item -Path $ReportPath -Destination $LocalJsonPath -Force -ErrorAction Stop
    Write-Verbose "Local JSON report saved: $LocalJsonPath"
}
catch {
    Write-Verbose "Warning: Could not save JSON report: $_"
}

# Convert to CSV for easy review (in Intune logs)
if ($Report.OrphanedProfiles.Count -gt 0) {
    try {
        $CsvData = $Report.OrphanedProfiles | Select-Object @{
            Name = "ComputerName"
            Expression = { $ComputerName }
        }, @{
            Name = "ProfileName"
            Expression = { $_.ProfileName }
        }, @{
            Name = "ProfilePath"
            Expression = { $_.ProfilePath }
        }, @{
            Name = "LastActivityTime"
            Expression = { $_.LastActivityTime }
        }, @{
            Name = "InactiveForDays"
            Expression = { $_.InactiveForDays }
        }, @{
            Name = "SizeMB"
            Expression = { $_.SizeMB }
        }, @{
            Name = "ExistsInOnPremAD"
            Expression = { $_.ExistsInOnPremAD }
        }, @{
            Name = "ExistsInEntraID"
            Expression = { $_.ExistsInEntraID }
        }, @{
            Name = "DetectedDate"
            Expression = { $_.DetectedDate }
        }
        
        $LocalCsvPath = Join-Path $LocalArchivePath "${ReportFileName}.csv"
        $CsvData | Export-Csv -Path $LocalCsvPath -NoTypeInformation -Force -ErrorAction Stop
        Write-Verbose "Local CSV report saved: $LocalCsvPath"
    }
    catch {
        Write-Verbose "Warning: Could not save CSV report: $_"
    }
}

# Output summary to Intune logs
Write-Output ""
Write-Output "============================================="
Write-Output "ORPHANED PROFILE DETECTION - REPORT SUMMARY"
Write-Output "============================================="
Write-Output "Computer: $ComputerName"
Write-Output "Report Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Output "Profiles Checked: $($Report.ProfilesChecked)"
Write-Output "Orphaned Profiles Found: $($Report.OrphanedCount)"
Write-Output "Inactivity Threshold: $($Report.InactivityDays) days"
Write-Output ""

if ($Report.OrphanedProfiles.Count -gt 0) {
    Write-Output "ORPHANED PROFILES DETECTED:"
    Write-Output "-----------------------------------------"
    
    $TotalSizeMB = 0
    foreach ($Profile in $Report.OrphanedProfiles) {
        $TotalSizeMB += $Profile.SizeMB
        Write-Output "  • Profile: $($Profile.ProfileName)"
        Write-Output "    Path: $($Profile.ProfilePath)"
        Write-Output "    Size: $($Profile.SizeMB) MB"
        Write-Output "    Last Activity: $($Profile.LastActivityTime)"
        Write-Output "    Inactive: $($Profile.InactiveForDays) days"
        Write-Output "    Exists in On-Prem AD: $($Profile.ExistsInOnPremAD)"
        Write-Output "    Exists in Entra ID: $($Profile.ExistsInEntraID)"
        Write-Output ""
    }
    
    Write-Output "SUMMARY:"
    Write-Output "-----------------------------------------"
    Write-Output "Total Orphaned Profiles: $($Report.OrphanedProfiles.Count)"
    Write-Output "Total Size (Recoverable): $([math]::Round($TotalSizeMB, 2)) MB"
    Write-Output ""
    Write-Output "ACTION REQUIRED:"
    Write-Output "Review profiles in Intune logs and determine if manual deletion is needed."
    Write-Output "Local reports saved to: $LocalArchivePath"
    Write-Output ""
}
else {
    Write-Output "No orphaned profiles found on this device."
    Write-Output "Device is healthy."
    Write-Output ""
}

Write-Output "============================================="
Write-Output ""

exit 0
